<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="shipping_service_wrapper" targetNamespace="http://enterprise.netbeans.org/bpel/shipping_service_wrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/shipping_service_wrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://infosys.tuwien.ac.at/aic10/ass1/dto/shipping">
    <import location="shipping_service.wsdl" namespace="http://infosys.tuwien.ac.at/aic10/ass1/dto/shipping"/>
    <plnk:partnerLinkType name="shipping_service_link_type">
        <plnk:role name="shipping_service_role" portType="ns:ShippingService"/>
    </plnk:partnerLinkType>
</definitions>

